### ISSUE TITLE
[Bug] Application crashes when missing snapshots.json

### ISSUE THREAD

**Issue by robwettach** [robwettach/webdiplomacy-poller#4]
When bootstrapping a new instance of the application, the app crashes with a `NullPointerException` when there are no previous games stored in `snapshots.json`:

```
$ export WEBDIP_POLLER_HOME=$(pwd)/local-config
$ ./build/install/webdiplomacy-poller/bin/webdiplomacy-poller
Username: robwettach
Password:
.java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.robwettach.webdiplomacy.poller.Main.main(Main.java:53)
Caused by: java.lang.NullPointerException
	at com.robwettach.webdiplomacy.poller.Main.checkForUpdates(Main.java:118)
	at com.robwettach.webdiplomacy.poller.Main.lambda$main$0(Main.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The issue is that we're looking in the [`notifications` map](https://github.com/robwettach/webdiplomacy-poller/blob/master/src/main/java/com/robwettach/webdiplomacy/poller/Main.java#L118) for the recently-found `gameId`, but not finding it.  We're assuming that when we ran [`prepopulateNotificationState`](https://github.com/robwettach/webdiplomacy-poller/blob/master/src/main/java/com/robwettach/webdiplomacy/poller/Main.java#L63) initially we prepopulated all known `gameId`s, but that's clearly wrong on first-run.

A simple solution might be to call `notifications.computeIfAbsent(id, (i) -> new GameNotifications(i, ...))` ([docs](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html#computeIfAbsent(K,java.util.function.Function))) instead of `notifications.get(id)`, guaranteeing that a `GameNotifications` instance will be returned.

A more complex solution would require pre-registering all expected `gameId`s and only retrieving game state and attempting to notify for those known games.

**Comment by robwettach** [comment]
I chose the easy way out for now by just generating a `GameNotifications` when we come across an unknown `gameId`
